from pagination.pagewise import PagewisePagination
from pagination.yearwise import YearPagination
from pagination.single_hit_case import SingleHitCase
from pagination.year_and_pagewise import YearAndPageWisePagination
